---
- name: Get url of latest Craft CLI release
  shell: curl --silent https://api.github.com/repos/rsanchez/craft-cli/releases/latest | /usr/bin/awk '/browser_download_url/ { print $2 }' | /usr/bin/sed 's/"//g'
  register: download_url
  when: not craft_cli_version
- name: Get url of latest Craft CLI release
  shell: echo "https://github.com/rsanchez/craft-cli/releases/download/$CRAFT_CLI_VERSION/craft.phar"
  register: download_url
  when: craft_cli_version
- name: Download and install Craft CLI to /usr/local/bin.
  get_url:
    url: {{ download_url.stdout }}
    dest: "{{ craft_cli_install_path }}/craft"
    mode: a+x